[WIP]feat:  Replace the editor with markdown
eggjs/egg-showcase-aliyun-blog pull request #3
Opened 2017-02-09 09:55 UTC by hacke2

- [ ] Replace the editor with markdown
- [ ] Improve document

2017-02-09 09:59 UTC, atian25 commented
markdown 的那个其实可以简化的,  最简单就是一个纯 textarea, 不提供可视化编辑, 就是渲染的时候 marked 渲染下而已. 刚好今天做了一个 nunjucks markdown 的 showcase: https://github.com/eggjs/egg-view-nunjucks/pull/10

2017-02-09 10:01 UTC, hacke2 commented
哈哈好的，就用这个了

2017-02-10 02:35 UTC, hacke2 commented
@atian25 帮忙下看看这个文档行不行

2017-02-13 02:36 UTC, atian25 requested changes

2017-02-13 02:36 UTC, atian25 commented on README.md
> +git clone git@github.com:blade254353074/react-router-lazy-import.git
what's this?

2017-02-13 02:36 UTC, atian25 commented on README.md
> +```
bash

2017-02-13 02:36 UTC, atian25 commented on package.json
> +    "install-node": "6.1.0"
remove

2017-04-11 01:26 UTC, atian25 commented
这个还做么?

2017-04-13 12:14 UTC, hacke2 commented
@atian25 https://github.com/eggjs/egg/issues/53#issuecomment-279282124 具体阿里云的使用我觉得还是阿里云的同学搞比较好

2018-12-18 06:42 UTC, closed without merging